name: Deploy Lambda Function

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'main'  # Specify your default branch here

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}  # Check out the specified branch

    - name: Set up AWS CLI
      run: |
        choco install awscli || exit 1

    - name: Configure AWS CLI for OIDC
      run: |
        # Install the necessary tools to use OIDC with GitHub Actions
        curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-windows-x86_64.zip" -o "awscliv2.zip"
        Expand-Archive awscliv2.zip -DestinationPath "C:\Program Files\Amazon\AWSCLI"
        & "C:\Program Files\Amazon\AWSCLI\aws.exe" --version

    - name: Configure AWS OIDC Authentication
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::975049994612:role/oidc
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: GitHubActions

    - name: Zip the function code
      run: |
        Compress-Archive -Path * -DestinationPath Function.zip

    - name: Deploy to Lambda
      run: |
        # Set function name directly for the chosen environment (stage)
        $functionName = "${{ secrets.AWS_LAMBDA_FUNCTION_STAGE }}"

        # Deploy Lambda function code
        aws lambda update-function-code --function-name $functionName --zip-file fileb://Function.zip || exit 1

    - name: Clean up
      run: |
        Remove-Item Function.zip -Force
