name: Deploy Lambda Function

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Install AWS CLI
      run: |
        # Download AWS CLI v2 zip
        Invoke-WebRequest "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-windows-x86_64.zip" -OutFile "awscliv2.zip"
        
        # Expand the archive into the target directory
        Expand-Archive -Path "awscliv2.zip" -DestinationPath "C:\Program Files\Amazon\AWSCLI" -Force
        
        # Check AWS CLI version
        & "C:\Program Files\Amazon\AWSCLI\aws.exe" --version

    - name: Configure AWS OIDC Authentication
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::975049994612:role/oidc
        aws-region: ${{ secrets.AWS_REGION }}
        role-session-name: GitHubActions

    - name: Zip the function code
      run: |
        pwsh -Command "Compress-Archive -Path * -DestinationPath Function.zip"

    - name: Deploy to Lambda
      run: |
        pwsh -Command |
          $functionName = "${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}"
          aws lambda update-function-code --function-name $functionName --zip-file fileb://Function.zip || exit 1

    - name: Clean up
      run: |
        pwsh -Command "Remove-Item Function.zip -Force"
