name: Deploy Lambda Function

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: Set up AWS CLI
      run: |
        choco install awscli || exit 1

    - name: Configure AWS OIDC Authentication
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::975049994612:role/oidc-lambda
        aws-region: ap-south-1
        role-session-name: GitHubActions
        audience: sts.amazonaws.com  # Add audience if necessary for OIDC authentication

    - name: Zip the function code
      run: |
        pwsh -Command "Compress-Archive -Path * -DestinationPath Function.zip"

    - name: Deploy to Lambda
      run: |
        pwsh -Command |
          $functionName = "${{ secrets.AWS_LAMBDA_FUNCTION_NAME }}"
          aws lambda update-function-code --function-name $functionName --zip-file fileb://Function.zip || exit 1

    - name: Clean up
      run: |
        pwsh -Command "Remove-Item Function.zip -Force"
